import { useRef, useMemo } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'

/**
 * Noise Terrain Flythrough — Infinite procedural terrain generated by a vertex
 * shader. Camera flies forward continuously. Mouse tilts the view. Fog fades
 * the horizon. Grid lines pulse with color based on height.
 */

const vertexShader = `
uniform float time;
uniform float speed;

varying float vHeight;
varying vec2 vUv;
varying float vFog;

// Simplex-ish noise
vec3 mod289(vec3 x) { return x - floor(x * (1.0/289.0)) * 289.0; }
vec2 mod289(vec2 x) { return x - floor(x * (1.0/289.0)) * 289.0; }
vec3 permute(vec3 x) { return mod289(((x*34.0)+1.0)*x); }

float snoise(vec2 v) {
  const vec4 C = vec4(0.211324865405187, 0.366025403784439,
                      -0.577350269189626, 0.024390243902439);
  vec2 i  = floor(v + dot(v, C.yy));
  vec2 x0 = v -   i + dot(i, C.xx);
  vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);
  vec4 x12 = x0.xyxy + C.xxzz;
  x12.xy -= i1;
  i = mod289(i);
  vec3 p = permute(permute(i.y + vec3(0.0, i1.y, 1.0)) + i.x + vec3(0.0, i1.x, 1.0));
  vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);
  m = m*m; m = m*m;
  vec3 x = 2.0 * fract(p * C.www) - 1.0;
  vec3 h = abs(x) - 0.5;
  vec3 ox = floor(x + 0.5);
  vec3 a0 = x - ox;
  m *= 1.79284291400159 - 0.85373472095314 * (a0*a0 + h*h);
  vec3 g;
  g.x = a0.x * x0.x + h.x * x0.y;
  g.yz = a0.yz * x12.xz + h.yz * x12.yw;
  return 130.0 * dot(m, g);
}

void main() {
  vUv = uv;
  vec3 pos = position;

  // Scroll terrain forward over time
  vec2 noiseCoord = pos.xz * 0.15 + vec2(0.0, time * speed);

  // Layered noise for interesting terrain
  float h = snoise(noiseCoord) * 1.5;
  h += snoise(noiseCoord * 2.0) * 0.7;
  h += snoise(noiseCoord * 4.0) * 0.3;
  h += snoise(noiseCoord * 8.0) * 0.1;

  pos.y += h;
  vHeight = h;

  // Distance-based fog
  vec4 mvPos = modelViewMatrix * vec4(pos, 1.0);
  vFog = smoothstep(5.0, 35.0, -mvPos.z);

  gl_Position = projectionMatrix * mvPos;
}
`

const fragmentShader = `
uniform float time;

varying float vHeight;
varying vec2 vUv;
varying float vFog;

void main() {
  // Height-based coloring
  vec3 deepColor = vec3(0.0, 0.03, 0.1);
  vec3 lowColor = vec3(0.0, 0.1, 0.3);
  vec3 midColor = vec3(0.0, 0.5, 0.6);
  vec3 highColor = vec3(0.0, 0.96, 0.83);
  vec3 peakColor = vec3(1.0, 0.4, 0.7);

  float h = (vHeight + 2.0) / 5.0;
  vec3 color = deepColor;
  color = mix(color, lowColor, smoothstep(0.0, 0.25, h));
  color = mix(color, midColor, smoothstep(0.25, 0.45, h));
  color = mix(color, highColor, smoothstep(0.45, 0.7, h));
  color = mix(color, peakColor, smoothstep(0.7, 1.0, h));

  // Grid wireframe overlay
  vec2 grid = abs(fract(vUv * vec2(80.0, 120.0)) - 0.5);
  float gridLine = 1.0 - smoothstep(0.42, 0.48, min(grid.x, grid.y));
  color += gridLine * color * 0.8;

  // Scanline effect
  float scanline = sin(vUv.y * 400.0 + time * 2.0) * 0.03;
  color += scanline;

  // Fog
  vec3 fogColor = vec3(0.0, 0.01, 0.04);
  color = mix(color, fogColor, vFog);

  gl_FragColor = vec4(color, 1.0);
}
`

export default function NoiseTerrain() {
  const meshRef = useRef()
  const groupRef = useRef()
  const { pointer } = useThree()
  const smoothTilt = useRef({ x: 0, y: 0 })

  const uniforms = useMemo(() => ({
    time: { value: 0 },
    speed: { value: 0.3 },
  }), [])

  useFrame(({ clock }) => {
    uniforms.time.value = clock.elapsedTime

    // Mouse tilt
    smoothTilt.current.x += (pointer.y * 0.15 - smoothTilt.current.x) * 0.03
    smoothTilt.current.y += (pointer.x * 0.2 - smoothTilt.current.y) * 0.03

    if (groupRef.current) {
      groupRef.current.rotation.x = -Math.PI * 0.38 + smoothTilt.current.x
      groupRef.current.rotation.z = smoothTilt.current.y
    }
  })

  return (
    <group ref={groupRef} rotation={[-Math.PI * 0.38, 0, 0]} position={[0, -1, 0]}>
      <mesh ref={meshRef}>
        <planeGeometry args={[40, 40, 200, 200]} />
        <shaderMaterial
          vertexShader={vertexShader}
          fragmentShader={fragmentShader}
          uniforms={uniforms}
          side={THREE.DoubleSide}
          wireframe={false}
        />
      </mesh>
    </group>
  )
}
